/**
 * Simulated butterfly sighting rows for dev/testing.
 * Coordinates include Central London (Trafalgar Square) and Serangoon, Singapore clusters.
 * Used by SupabaseDBManager.seedTestData().
 */

const now = new Date()

export const SIMULATED_SIGHTINGS = [
  {
    snap_display_name: "test_user_1",
    latitude: 51.5074, longitude: -0.1278,
    identified_at: new Date(now.getTime() - 5 * 60000).toISOString(),
    species_scientific_name: "Danaus plexippus",
    species_common_names: ["Monarch butterfly"],
    species_probability: 0.97,
    species_red_list: "LEAST_CONCERN",
    species_description: "Large orange and black migratory butterfly found across North America.",
    species_danger: ["harmless to human health"],
    species_role: ["pollinator", "beneficial"],
    species_image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Monarch_Butterfly_Danaus_plexippus.jpg/320px-Monarch_Butterfly_Danaus_plexippus.jpg",
    species_taxonomy: { kingdom: "Animalia", phylum: "Arthropoda", class: "Insecta", order: "Lepidoptera", family: "Nymphalidae", genus: "Danaus" },
    wing_texture_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testWingTexture.jpeg",
    wing_opacity_map_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testOpacityTexture.jpeg",
  },
  {
    snap_display_name: "test_user_2",
    latitude: 51.5091, longitude: -0.1245,
    identified_at: new Date(now.getTime() - 20 * 60000).toISOString(),
    species_scientific_name: "Papilio machaon",
    species_common_names: ["Old World swallowtail", "Common yellow swallowtail"],
    species_probability: 0.91,
    species_red_list: "LEAST_CONCERN",
    species_description: "Striking yellow butterfly with black tiger-stripe pattern and blue hindwing patches.",
    species_danger: ["harmless to human health"],
    species_role: ["pollinator"],
    species_image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Papilio_machaon_2.jpg/320px-Papilio_machaon_2.jpg",
    species_taxonomy: { kingdom: "Animalia", phylum: "Arthropoda", class: "Insecta", order: "Lepidoptera", family: "Papilionidae", genus: "Papilio" },
    wing_texture_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testWingTexture.jpeg",
    wing_opacity_map_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testOpacityTexture.jpeg",
  },
  {
    snap_display_name: "test_user_1",
    latitude: 51.5058, longitude: -0.1320,
    identified_at: new Date(now.getTime() - 45 * 60000).toISOString(),
    species_scientific_name: "Morpho peleides",
    species_common_names: ["Blue morpho"],
    species_probability: 0.88,
    species_red_list: "LEAST_CONCERN",
    species_description: "Iconic iridescent blue tropical butterfly; the blue is structural coloration, not pigment.",
    species_danger: ["harmless to human health"],
    species_role: ["beneficial"],
    species_image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Morpho_peleides_limpida.jpg/320px-Morpho_peleides_limpida.jpg",
    species_taxonomy: { kingdom: "Animalia", phylum: "Arthropoda", class: "Insecta", order: "Lepidoptera", family: "Nymphalidae", genus: "Morpho" },
    wing_texture_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testWingTexture.jpeg",
    wing_opacity_map_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testOpacityTexture.jpeg",
  },
  {
    snap_display_name: "test_user_3",
    latitude: 51.5105, longitude: -0.1302,
    identified_at: new Date(now.getTime() - 90 * 60000).toISOString(),
    species_scientific_name: "Vanessa cardui",
    species_common_names: ["Painted lady"],
    species_probability: 0.94,
    species_red_list: "LEAST_CONCERN",
    species_description: "The world's most widespread butterfly species, found on every continent except Antarctica.",
    species_danger: ["harmless to human health"],
    species_role: ["pollinator", "beneficial"],
    species_image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Vanessa_cardui_f.jpg/320px-Vanessa_cardui_f.jpg",
    species_taxonomy: { kingdom: "Animalia", phylum: "Arthropoda", class: "Insecta", order: "Lepidoptera", family: "Nymphalidae", genus: "Vanessa" },
    wing_texture_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testWingTexture.jpeg",
    wing_opacity_map_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testOpacityTexture.jpeg",
  },
  {
    snap_display_name: "test_user_2",
    latitude: 51.5042, longitude: -0.1261,
    identified_at: new Date(now.getTime() - 120 * 60000).toISOString(),
    species_scientific_name: "Vanessa atalanta",
    species_common_names: ["Red admiral"],
    species_probability: 0.89,
    species_red_list: "LEAST_CONCERN",
    species_description: "Bold black butterfly with striking red-orange bands and white spots near the wing tips.",
    species_danger: ["harmless to human health"],
    species_role: ["pollinator"],
    species_image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Vanessa_atalanta_f_Luc_Viatour.jpg/320px-Vanessa_atalanta_f_Luc_Viatour.jpg",
    species_taxonomy: { kingdom: "Animalia", phylum: "Arthropoda", class: "Insecta", order: "Lepidoptera", family: "Nymphalidae", genus: "Vanessa" },
    wing_texture_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testWingTexture.jpeg",
    wing_opacity_map_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testOpacityTexture.jpeg",
  },
  // Serangoon, Singapore cluster
  {
    snap_display_name: "test_user_1",
    latitude: 1.3501, longitude: 103.8718,
    identified_at: new Date(now.getTime() - 10 * 60000).toISOString(),
    species_scientific_name: "Papilio demoleus",
    species_common_names: ["Lime butterfly", "Chequered swallowtail"],
    species_probability: 0.95,
    species_red_list: "LEAST_CONCERN",
    species_description: "Common swallowtail widespread across Asia; larvae feed on citrus plants.",
    species_danger: ["harmless to human health"],
    species_role: ["pollinator", "beneficial"],
    species_image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Papilio_demoleus_malayanus_Penang.jpg/320px-Papilio_demoleus_malayanus_Penang.jpg",
    species_taxonomy: { kingdom: "Animalia", phylum: "Arthropoda", class: "Insecta", order: "Lepidoptera", family: "Papilionidae", genus: "Papilio" },
    wing_texture_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testWingTexture.jpeg",
    wing_opacity_map_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testOpacityTexture.jpeg",
  },
  {
    snap_display_name: "test_user_3",
    latitude: 1.3563, longitude: 103.8749,
    identified_at: new Date(now.getTime() - 35 * 60000).toISOString(),
    species_scientific_name: "Euploea core",
    species_common_names: ["Common crow"],
    species_probability: 0.92,
    species_red_list: "LEAST_CONCERN",
    species_description: "Dark brownish-black butterfly with small white spots; one of the most common species in Singapore.",
    species_danger: ["harmless to human health"],
    species_role: ["pollinator"],
    species_image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Euploea_core_Kkb.jpg/320px-Euploea_core_Kkb.jpg",
    species_taxonomy: { kingdom: "Animalia", phylum: "Arthropoda", class: "Insecta", order: "Lepidoptera", family: "Nymphalidae", genus: "Euploea" },
    wing_texture_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testWingTexture.jpeg",
    wing_opacity_map_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testOpacityTexture.jpeg",
  },
  {
    snap_display_name: "test_user_2",
    latitude: 1.3588, longitude: 103.8864,
    identified_at: new Date(now.getTime() - 60 * 60000).toISOString(),
    species_scientific_name: "Catopsilia pomona",
    species_common_names: ["Lemon emigrant", "Common emigrant"],
    species_probability: 0.87,
    species_red_list: "LEAST_CONCERN",
    species_description: "Medium-sized yellow or white butterfly; a strong migratory flier common in urban Singapore gardens.",
    species_danger: ["harmless to human health"],
    species_role: ["pollinator", "beneficial"],
    species_image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Catopsilia_pomona_f_Luc_Viatour.jpg/320px-Catopsilia_pomona_f_Luc_Viatour.jpg",
    species_taxonomy: { kingdom: "Animalia", phylum: "Arthropoda", class: "Insecta", order: "Lepidoptera", family: "Pieridae", genus: "Catopsilia" },
    wing_texture_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testWingTexture.jpeg",
    wing_opacity_map_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testOpacityTexture.jpeg",
  },
  {
    snap_display_name: "test_user_1",
    latitude: 1.3472, longitude: 103.8660,
    identified_at: new Date(now.getTime() - 85 * 60000).toISOString(),
    species_scientific_name: "Junonia almana",
    species_common_names: ["Peacock pansy"],
    species_probability: 0.93,
    species_red_list: "LEAST_CONCERN",
    species_description: "Bright orange butterfly with striking eyespots on all four wings; found in open grassy areas.",
    species_danger: ["harmless to human health"],
    species_role: ["pollinator"],
    species_image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Junonia_almana_DSF.jpg/320px-Junonia_almana_DSF.jpg",
    species_taxonomy: { kingdom: "Animalia", phylum: "Arthropoda", class: "Insecta", order: "Lepidoptera", family: "Nymphalidae", genus: "Junonia" },
    wing_texture_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testWingTexture.jpeg",
    wing_opacity_map_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testOpacityTexture.jpeg",
  },
  {
    snap_display_name: "test_user_3",
    latitude: 1.3540, longitude: 103.8800,
    identified_at: new Date(now.getTime() - 110 * 60000).toISOString(),
    species_scientific_name: "Troides helena",
    species_common_names: ["Common birdwing"],
    species_probability: 0.90,
    species_red_list: "LEAST_CONCERN",
    species_description: "Large birdwing butterfly with striking black and gold wings; a protected species in Singapore.",
    species_danger: ["harmless to human health"],
    species_role: ["pollinator", "beneficial"],
    species_image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Troides_helena_male_Penang.jpg/320px-Troides_helena_male_Penang.jpg",
    species_taxonomy: { kingdom: "Animalia", phylum: "Arthropoda", class: "Insecta", order: "Lepidoptera", family: "Papilionidae", genus: "Troides" },
    wing_texture_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testWingTexture.jpeg",
    wing_opacity_map_url: "https://jwdbbiewmfxiiryhjxbd.snapcloud.dev/storage/v1/object/public/butterfly-photos/wings/testOpacityTexture.jpeg",
  },
]
